config:
  env: 'darkroom_heldout'
  envs: 100000
  envs_eval: 100
  hists: 1
  samples: 1
  H: 20
  dim: 9
  lin_d: 2
  var: 0.0
  cov: 0.0
  env_id_start: -1
  env_id_end: -1
  embd: 64
  head: 4
  layer: 4
  lr_init: 0.000002  # Initial learning rate
  lr_peak: 0.0003   # Peak learning rate for cosine schedule
  batch_size: 128
  beta_1: 0.9
  beta_2: 0.99
  dropout: 0.1
  shuffle: False
  num_epochs: 1000
  epoch: -1
  test_cov: -1.0
  horizon: -1
  n_eval: 100
  seed: 0
  max_seq_len: 1024
  train_history_len: 300
  grad_clip: 1.0

ppo:
  total_timesteps: 50000
  timesteps_per_batch: 2048
  k_epochs: 80
  eps_clip: 0.2
  gamma: 0.99
  lr_actor: 0.0003
  lr_critic: 0.001
  patience: 7